dist: xenial
language: go

go:
  - "1.9"
  - "1.10"
  - master

install:
  - sudo apt-get install -y tcpdump libpcap-dev openssl libssl-dev
  - go get -t -v ./... || true
  - cd $GOPATH/src/github.com/mpiraux/pigotls && make
  - cd $GOPATH/src/github.com/mpiraux/ls-qpack-go && make
